apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: support-priority-project
  namespace: argocd
spec:
  description: Projet ArgoCD pour l'API de priorisation de tickets support
  sourceRepos:
    #- <URL_DE_VOTRE_FORK>
  destinations:
    - namespace: support-priority
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
