apiVersion: v1
kind: Service
metadata:
  name: support-priority-api
  namespace: support-priority
spec:
  selector:
    app: support-priority-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
