namespace: support-priority
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: support-priority-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
